name: Javascript CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: npm install, test
        run: |
          npm install
          npm test
          npm run report-cov
        env:
          CI: true
          CODECOVE_TOKEN: fb303a82-9f9d-4739-9200-aaf407bbc4ef